### ISSUE TITLE
FCC does not connect to MQTT 

### ISSUE THREAD

**Issue by vm-wylbur-pi** [vm-wylbur-pi/fof_tests#2]
`mosquitto` is running, and in its log I can see "New client connected from ... as Flower_Control_Center" when I refresh the FCC's `index.html`. Later in the log I can see a flower's heartbeat, so `mosquitto` seems ok. However, there's no flower in the FCC, so I can't send commands from there. 

Something I have overlooked? What should I test?

**Comment by vm-wylbur** [comment]
There was a git merge header mixed into the FCC's javascript. George fixed it.
